version: "2"
services:
  scheduler:
    container_name: scheduler
#    restart: always
    build: ./
#    ports:
#      - "4840:4840"
#    network_mode: bridge
    networks:
      - i40network
    external_links:
      - discoveryserver
      - repository
networks:
    i40network:
        external:
            name: i40network