version: "2"
services:
  repodb:
    container_name: repodb
    image: mongo
    volumes:
      - /data/db
      - /data/configdb
    ports:
      - "27017:27017"
  repository:
    container_name: repository
#    restart: always
    build: ./
    ports:
      - "8080:8080"
      - "30000-30100:30000-30100"
    links:
      - mongodb
    depends_on:
      - mongodb