version: "2"
services:
  repodb:
    container_name: repodb
    image: mongo
    volumes:
      - /data/db
      - /data/configdb
    ports:
      - "27018:27018"
    network_mode: bridge
  repository:
    container_name: repository
    hostname: repository
#    restart: always
    build: ./
    ports:
      - "8090:8090"
      - "30000-30100:30000-30100"
    network_mode: bridge
    links:
      - repodb
    external_links:
      - discoveryserver
    depends_on:
      - repodb