version: "2"
services:
  controldb:
    container_name: controldb
    image: mongo
    volumes:
      - /data/db
      - /data/configdb
    ports:
      - "27017:27017"
    network_mode: bridge
  control:
    container_name: control
#    restart: always
    build: ./
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
#      - "30000-30100:30000-30100"
    network_mode: bridge
    links:
      - controldb
    external_links:
      - discoveryserver
      - repository
    depends_on:
      - controldb