version: "2"
services:
  realprinter:
    container_name: realprinter
    hostname: realprinter
    privileged: true
#    restart: always
    build: ./
    ports:
      - "6666:6666"
#    network_mode: bridge
    networks:
      - i40network
    tty: true
#    interactive: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
#      - /etc/cups:/etc/cups
#      - /var/run/cups:/var/run/cups
networks:
    i40network:
        external:
            name: i40network