version: "2"
services:
  discoveryserver:
    container_name: discoveryserver
    hostname: discoveryserver
#    restart: always
    build: ./
    ports:
      - "4840:4840"
#    network_mode: bridge
    networks:
      - i40network
networks:
    i40network:
        external:
            name: i40network